### ISSUE TITLE
page not found on login

### ISSUE THREAD

**Issue by rubo77** [Awesome-Technologies/synapse-admin#1]
I installed it with npm and when I start I am successfully redirected to the page in the borowser, where I can login. But When I try to login with my admoin user on my own homeserver, I get the error "Page not Found" on http://localhost:6075/user-admin/list

**Comment by tatdatpham** [comment]
+1, got same problem

**Comment by awesome-manuel** [comment]
Please try again with latest master branch.

**Comment by awesome-manuel** [comment]
We did a complete rewrite using `react-admin`, so this is probably outdated.
