### ISSUE TITLE
Show room events count for filtering rooms by size in database

### ISSUE THREAD

**Issue by MurzNN** [Awesome-Technologies/synapse-admin#10]
Will be good to see room events count column in Rooms tab, is this possible? Or any other way to understand estimate size of room in database.

**Comment by awesome-manuel** [comment]
The whole admin room API of synapse needs some improvements. As soon as we have it in synapse we can also show it in synapse-admin.

**Comment by dklimpel** [comment]
Related to: https://github.com/matrix-org/synapse/pull/7225

**Comment by awesome-manuel** [comment]
Also related to: https://github.com/matrix-org/synapse/pull/7317
