### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by Aragur** [Awesome-Technologies/synapse-admin#102]
Hey I'm running this on my Helios64 wich is a ARM64 SoC.
Could you please add support for ARM devices (this would also allow this to run on RPis)

**Comment by awesome-manuel** [comment]
This software is based on nodejs, so there is nothing that needs to be changed for ARM. Do you refer to the Docker images?

**Comment by Aragur** [comment]
Yes I do refer to the Docker images

**Comment by awesome-manuel** [comment]
Do you know how to do this using the Docker-Hub internal builder?

**Comment by awesome-manuel** [comment]
Relates to #69

**Comment by awesome-manuel** [comment]
Fixed by 28862035943290d4d26cf111d1a2a405db93680d
