### ISSUE TITLE
Import csv creates user name with random id

### ISSUE THREAD

**Issue by toshanmugaraj** [Awesome-Technologies/synapse-admin#103]
Importing csv files creates random user id. How to enable/ disable various modes from admin UI.

**Comment by awesome-michael** [comment]
If you provide user ids in your csv file the import should use these instead of generating random ones.

**Comment by sm2x** [comment]
is user-ids equivalent to id?  because I tried to put the supposed user-id as 'id' but I end up getting random user-ids
this is the given csv example:
id,displayname,password,is_guest,admin,deactivated
@user006:my-domain.org,my-display-name,my-password,0,0,0
