### ISSUE TITLE
change listening IP address

### ISSUE THREAD

**Issue by seth586** [Awesome-Technologies/synapse-admin#106]
I am running synapse in a FreeBSD jail, so my browser does not have access to localhost:3000, is there any way to change the UI to listen on a different IP address on my lan?

Thanks!

**Comment by dklimpel** [comment]
See here:
You can use ```yarn build``` instead ```yarn start``` 
https://github.com/Awesome-Technologies/synapse-admin/issues/77#issuecomment-715203965
