### ISSUE TITLE
Allow fixed home server

### ISSUE THREAD

**Issue by jokey2k** [Awesome-Technologies/synapse-admin#114]
Currently the home server needs to be specified. It would be great both from user experience and security perspective to limit it to a predefined value

**Comment by awesome-michael** [comment]
I'm not sure if I understand your request. Do you want to configure a fixed homeserver for your instance of synapse-admin? Maybe someone want to host a synapse-admin for others. That would not be possible with predefined homeservers. What would be the security benefit of predefined values?

**Comment by deltafactory** [comment]
Not sure about the security benefit, but it would improve UX when using it as a tool for a specific homeserver. It could be implemented as a build-time configurable option.
