### ISSUE TITLE
seeing /null inside the URLs in the log

### ISSUE THREAD

**Issue by christoofar** [Awesome-Technologies/synapse-admin#117]
Using the Docker container, I can't seem to figure out how to get the URLs to mesh.  /_synapse and /_matrix are both done by reverse proxy so they appear from a unified public address but I can't seem to get that going for this container.

**Comment by awesome-michael** [comment]
Synapse-Admin just uses the `/_matrix` and `/_synapse` endpoints of the synapse instance. You don't have to publish these pathes for the Synapse-Admin container itself.
