### ISSUE TITLE
Rooms with no name

### ISSUE THREAD

**Issue by the-moog** [Awesome-Technologies/synapse-admin#119]
It could be that my server has been round since a very early release but many of the (I think unused) rooms have no name in the room list.
Perhaps replace the name with some other identity in this case?
It looks like some of the unnamed rooms are personal 1:1 chats.
Perhaps add a 1:1 column?

**Comment by awesome-michael** [comment]
Yes, 1:1 rooms don't have a name. The client (e.g. Element) renames them itself.
I thought about having a filter for 1:1 rooms, maybe a column would we nice too.

**Comment by the-moog** [comment]
Perhaps, as Synapse does not have a name for them, the name column could contain the two parties names, e.g.  Bob<->Alice.  A filter switch is also a very good idea.

**Comment by aaronraimist** [comment]
Yeah a column to see the room ID would be nice

Right now when rooms have no name it gets pretty difficult to tell what is what
<img width="1803" alt="Screen Shot" src="https://user-images.githubusercontent.com/5855073/115101069-e9704000-9f06-11eb-8d9c-2613e4af6fa6.png">

**Comment by waclaw66** [comment]
Empty room names are quite anoying, when you are looking for the right one. Synapse-admin should generate them similarly as Element, e.g. `Bob, Alice` or `Bob, Alice, Tom and 123 others`.

> 
> 
> Perhaps, as Synapse does not have a name for them, the name column could contain the two parties names, e.g. Bob<->Alice. A filter switch is also a very good idea.

**Comment by awesome-manuel** [comment]
> Yeah a column to see the room ID would be nice
This is implemented in 229518e45682306eeef4a3f3af38d1f69fecf485

Adding user names is not easily possible since that information is not provided by the room list endpoint.
