### ISSUE TITLE
How should I install

### ISSUE THREAD

**Issue by fkcctv1** [Awesome-Technologies/synapse-admin#12]
How should I install, can you give me a specific installation tutorial?

**Comment by rubo77** [comment]
The Readme states, how to do it, what else do you need? where are you stuck?

**Comment by fkcctv1** [comment]
I have a vps on Ubuntu 19, how do I use the built using react-admin. Command instead?

**Comment by fkcctv1** [comment]
What necessary software do I need to install first?

What command should I enter to start the installation

**Comment by awesome-manuel** [comment]
@fkcctv1 I hope you're aware that this is not a desktop application. It's a web app which means it basically runs a web server and you can access it with a browser.
The command `yarn` is a packages manager for `nodejs`. Using Ubuntu you can install it with `snap install node`.
The commands in the README.md will download the required dependencies and then start a development web server on your local machine.

**Comment by fkcctv1** [comment]
root@vultr:~# snap install node
error: snap "node" is not available on stable but is available to install on the following
       channels:

       edge       snap install --edge node

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info node'.


what should I do?

**Comment by fkcctv1** [comment]
> 自述文件指出，该怎么做，还需要什么？你困在哪里？

I have no idea what I should do, I hope you can guide me step by step, I will be very grateful

**Comment by awesome-manuel** [comment]
Since `node` has several channels, you could select `12/stable` using `snap install --channel=12/stable node`.

**Comment by fkcctv1** [comment]
> Since `node` has several channels, you could select `12/stable` using `snap install --channel=12/stable node`.

root@vultr:~# snap install --channel=12/stable node
error: This revision of snap "node" was published using classic confinement and thus may perform
       arbitrary system changes outside of the security sandbox that snaps are usually confined to,
       which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.

what should I do?

**Comment by fkcctv1** [comment]
> Since `node` has several channels, you could select `12/stable` using `snap install --channel=12/stable node`.

I am a computer idiot, thank you very much for your help,

**Comment by fkcctv1** [comment]
> Since `node` has several channels, you could select `12/stable` using `snap install --channel=12/stable node`.
root@vultr:~# yarn install synapse-admin
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

what should I do

**Comment by fkcctv1** [comment]
> The Readme states, how to do it, what else do you need? where are you stuck?

root@vultr:~# yarn install synapse-admin
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

what should I do

**Comment by awesome-manuel** [comment]
Sorry @fkcctv1 this tool is currently not suitable for beginners.
You could also try running our Docker container: https://hub.docker.com/r/awesometechnologies/synapse-admin

**Comment by fkcctv1** [comment]
Thank you

**Comment by fkcctv1** [comment]
> Sorry @fkcctv1 this tool is currently not suitable for beginners.
> You could also try running our Docker container: https://hub.docker.com/r/awesometechnologies/synapse-admin

Thank you

**Comment by awesome-manuel** [comment]
OK, I try to explain it really step by step:
You have two options:
1) Download the source code from github and run using nodejs
2) Run the Docker container

Steps for 1):
- install `git`: `apt install git`
- install `nodejs`: `snap install --channel=12/stable --classic node`
- download the source code: `git clone https://github.com/Awesome-Technologies/synapse-admin.git`
- go into download directory: `cd synapse-admin`
- download dependencies: `yarn install`
- start web server: `yarn start`

Steps for 2):
- run the Docker container: `docker run -p8080:80 awesometechnologies/synapse-admin`
- go to http://localhost:8080

**Comment by fkcctv1** [comment]
> OK, I try to explain it really step by step:
> You have two options:
> 
> 1. Download the source code from github and run using nodejs
> 2. Run the Docker container
> 
> Steps for 1):
> 
> * install `git`: `apt install git`
> * install `nodejs`: `snap install --channel=12/stable --classic node`
> * download the source code: `git clone https://github.com/Awesome-Technologies/synapse-admin.git`
> * go into download directory: `cd synapse-admin`
> * download dependencies: `yarn install`
> * start web server: `yarn start`
> 
> Steps for 2):
> 
> * run the Docker container: `docker run -p8080:80 awesometechnologies/synapse-admin`
> * go to http://localhost:8080

thank you very much for your help！！！

Now there is a new question, Failed to fetch after login....

I installed synapse through yunohost 。I set myself as an administrator using the following command
su --command="psql matrix_synapse" postgres <<< "UPDATE users SET admin = 1 WHERE name = '@test:xxxxxxcom'"

**Comment by fkcctv1** [comment]
https://github.com/YunoHost-Apps/synapse_ynh

This is their URL

After logging in now, prompt Failed to fetch

**Comment by fkcctv1** [comment]
Is it necessary to install synapse admin and synapse on the same server?

**Comment by eMPee584** [comment]
> Is it necessary to install synapse admin and synapse on the same server?

Seems not to be; I also tried that :sweat_smile:

**Comment by tonytonyistony** [comment]
> OK, I try to explain it really step by step: You have two options:
> 
>     1. Download the source code from github and run using nodejs
> 
>     2. Run the Docker container
> 
> 
> Steps for 1):
> 
>     * install `git`: `apt install git`
> 
>     * install `nodejs`: `snap install --channel=12/stable --classic node`
> 
>     * download the source code: `git clone https://github.com/Awesome-Technologies/synapse-admin.git`
> 
>     * go into download directory: `cd synapse-admin`
> 
>     * download dependencies: `yarn install`
> 
>     * start web server: `yarn start`
> 
> 
> Steps for 2):
> 
>     * run the Docker container: `docker run -p8080:80 awesometechnologies/synapse-admin`
> 
>     * go to http://localhost:8080

Is there a reason this isn't in your readme file for people that aren't experts?
