### ISSUE TITLE
select multiple media to delete from users and rooms 

### ISSUE THREAD

**Issue by githuberyt** [Awesome-Technologies/synapse-admin#121]
#118 select multiple media to delete from users and rooms

**Comment by githuberyt** [comment]
It's an essential feature to moderate synapse servers 
I hope you develop it soon thank you

**Comment by JuniorJPDJ** [comment]
bump

**Comment by wvffle** [comment]
It'd be nice to also be able to select rooms that will be removed.

**Comment by JuniorJPDJ** [comment]
@wvffle what do you mean?

**Comment by wvffle** [comment]
> @wvffle what do you mean?

![image](https://user-images.githubusercontent.com/13330620/126821268-13064bcb-5eea-41d7-9418-dd31074cae3b.png)
I mean the rooms, from the user view

**Comment by KeenMaron** [comment]
Any update to this?
The button "delete user data" does not delete all media. I've to delete every single file one by one. After that the button "delete user data" has a effect => the entry under media for the specific user disappears finally.

**Comment by awesome-manuel** [comment]
Media can be deleted in "media" tab of the user.
