### ISSUE TITLE
Is it possible to prefill the login form?

### ISSUE THREAD

**Issue by magoralczyk** [Awesome-Technologies/synapse-admin#123]
I have one admin user for my families synapse homeserver and the synapse-admin interface is obviously not accessible from the internet. Is it possible to prefill the user, password and url or at least user and url in the login screen? I have searched the files and folders but have not found the right place.

**Comment by rkfg** [comment]
You can specify them [here](https://github.com/Awesome-Technologies/synapse-admin/blob/c6b6e54617265490f9516e095abe40086f5b33df/src/components/LoginPage.js#L231) in the `initialValues` prop. Like this:
```js
return (
    <Form
      initialValues={{ base_url: base_url, username: 'admin', password: 'notveryobviouspassword' }}
```
The base_url seem to be saved to the browser local storage so you only need to enter it once.

**Comment by awesome-manuel** [comment]
Why not use the password manager of your browser?
