### ISSUE TITLE
Button "Erase User Data"

### ISSUE THREAD

**Issue by laicon188** [Awesome-Technologies/synapse-admin#128]
Hello everyone.

Do anyone know how to hide or disable button"Erase User Data".
If I accidentally press this button, user will be deleted without any confirmation.

**Comment by laicon188** [comment]
Or maybe someone know how to increase timeout to "undo" changes.

**Comment by dklimpel** [comment]
In the current version (0.8.0) a confirmation dialog appears.

**Comment by laicon188** [comment]
Thats greate news.
Thank you.
