### ISSUE TITLE
docker pull awesometechnologies/synapse-admin 

### ISSUE THREAD

**Issue by fkcctv1** [Awesome-Technologies/synapse-admin#13]
root@vultr:~# snap install docker
2020-03-03T09:53:44Z INFO Waiting for restart...
docker 18.09.9 from Canonical✓ installed
root@vultr:~# docker pull awesometechnologies/synapse-admin
Using default tag: latest
latest: Pulling from awesometechnologies/synapse-admin
4167d3e14976: Pull complete 
db94a93dfca0: Pull complete 
556f669bc8ac: Pull complete 
acca8aceb5b6: Pull complete 
Digest: sha256:5dde3eede21c9f8459bfadac1db67e4964dcd31ec995415b13e0e31572948094
Status: Downloaded newer image for awesometechnologies/synapse-admin:latest
root@vultr:~# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by fkcctv1** [comment]
What should i do？

**Comment by rubo77** [comment]
you must not install with yarn, if you use docker, use something like

    $ docker run <containername>

pls read the docker manual

**Comment by Routhinator** [comment]
The problem here is that the dockerfile does not supply a default COMMAND entry and therefore is not usable as you've created it without some explaination of how to launch the container @rubo77
