### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by sourav-majumdar-math** [Awesome-Technologies/synapse-admin#141]
When I try to run `docker run -p 8080:80 awesometechnologies/synapse-admin` I get the following error, 
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint vibrant_chatelet (872b899a95f807c06b34cf71cef78f95553f017bec0766669c09fb6e749a89dc): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.
```
I am using an Ubuntu 20.04 server

**Comment by awesome-michael** [comment]
The error tells you: "address already in use". So you can't use port 8080 as it is already used by another service. You can choose another port for synapse-admin
