### ISSUE TITLE
GDPR compliant delete does not delete users media and profile images

### ISSUE THREAD

**Issue by vsatmydynipnet** [Awesome-Technologies/synapse-admin#147]
If one deletes a user, especialy if more then one is marked, local_content and local_thumbnails still exists and are not deleted. to be GDPR compliant and also friendly to server space, media store must be cleaned up before deactivating the user.

**Comment by dklimpel** [comment]
This is a GUI for https://github.com/matrix-org/synapse
You can see the doc here: https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#deactivate-account
If this is a bug, then it is a bug of Synapse.

**Comment by vsatmydynipnet** [comment]
Ah, sorry, my fault.  But may i ask for an enhancement:

- addding a "delete media of deactivated users" job somewhere in synapse-admin. 

it is already possible to do this for user by user, but if you have to delete stuff of lot of users a mass job would be great. I have to do this for 1500 users which was created by bridges. they are deactivated, but their media remains on the server.

**Comment by dklimpel** [comment]
See: https://github.com/Awesome-Technologies/synapse-admin/issues/121
If this is implemented, you get a solution.
