### ISSUE TITLE
Homeserver cannot be accessed via http (only https)

### ISSUE THREAD

**Issue by fkcctv1** [Awesome-Technologies/synapse-admin#15]
I installed synapse through yunohost 。I set myself as an administrator using the following command
su --command="psql matrix_synapse" postgres <<< "UPDATE users SET admin = 1 WHERE name = '@test:xxxx.com'"

docker run -p8080:80 awesometechnologies/synapse-admin
 log in ：http://localhost:8080

prompt Failed to fetch

**Comment by awesome-manuel** [comment]
You need at least synapse v1.9.1

**Comment by jeremiah-k** [comment]
I'm having this issue with synapse version 1.12.3 installed via the Debian repo and the latest synapse-admin docker image.

**Comment by awesome-manuel** [comment]
Right now the URL is always changed to `https`. Maybe we should not be smarter than the admin and also allow `http`.

**Comment by SuperSandro2000** [comment]
This would be required if you want to se a local connection to synapse which has no https.

**Comment by jeremiah-k** [comment]
> Right now the URL is always changed to `https`. Maybe we should not be smarter than the admin and also allow `http`.

I can't tell if you are being condescending or trying to be helpful.

I'm hosting both matrix-synapse and synapse-admin on a VPS and I forward the synapse-admin docker port via ssh tunnel to my machine locally.  I am accessing synapse-admin via http://localhost:9090 which causes no issues. I log try to log into my homeserver which is https and use its fqdn.

I would very much like to "not be smarter than the admin" and get this to work, so which URL is always changed to https and where are we supposed allow http?

Thanks!

**Comment by awesome-manuel** [comment]
@teutat3s added this "feature" in this commit: 40b5031550e9720aeac4f9817d109cd1d4b83892

**Comment by awesome-manuel** [comment]
Fixed in dd022eab04d19ad1b11274c07b7cc622530442a3
