### ISSUE TITLE
CSV Import no longer working

### ISSUE THREAD

**Issue by Fail-Unsafe** [Awesome-Technologies/synapse-admin#153]
Matrix Synapse v1.35.1
Synapse-Admin (0.8.1)

The button CSV Import no longer works.

![Bildschirmfoto_2021-06-07_19-41-52](https://user-images.githubusercontent.com/26485846/121064931-79748c80-c7c8-11eb-8017-30e2273f51c0.png)

**Comment by dklimpel** [comment]
You can open the import page manually `/#/import_users`.
This ist only a workaround.
