### ISSUE TITLE
Able to login Synapse-admin but failed to fetch data.

### ISSUE THREAD

**Issue by gonzalloe** [Awesome-Technologies/synapse-admin#157]
I have successfully download the source code from Github and run using `nodejs`.
![image](https://user-images.githubusercontent.com/61778096/122060668-5e38fb00-ce20-11eb-8d2e-6a6cd51df2a4.png)

 Everything work fine until I login, no data are shown on the interface. 
![image](https://user-images.githubusercontent.com/61778096/122061852-7c532b00-ce21-11eb-895a-ba9427964eb9.png)

I have also added a direction to /_synapse/admin endpoint, but this doesn't seem to work for me.
![image](https://user-images.githubusercontent.com/61778096/122060356-15814200-ce20-11eb-88d6-3744db110b2f.png)

_Note that, my matrix server has dual NICs (1 for public and 1 for private network). The private network interface is stopped by our infrastructure team. So, I only can access to the server through public IP. 
However, the IP address shown on `On Your Network` at first picture above is my private network. Is that related to this issue?_

**Comment by dklimpel** [comment]
You must `/_synapse/admin` forward to Synapse, not o synapse-admin.

**Comment by dklimpel** [comment]
Yes, you have to `proxy_pass` this location to your synapse server. eg. localhost:8008

**Comment by gonzalloe** [comment]
It works! Appreciate that.
