### ISSUE TITLE
Fully delete user account

### ISSUE THREAD

**Issue by gonzalloe** [Awesome-Technologies/synapse-admin#158]
Do we manage to fully delete user account instead of just deactivate them using this API?

**Comment by dklimpel** [comment]
What happens you can see here: https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#deactivate-account

This is the documentation for deactivate / delete.

**Comment by awesome-manuel** [comment]
With "fully delete" you mean delete from the database? This is generally a bad idea, since a user can simply register this user ID again.

**Comment by DoM1niC** [comment]
in my case I might to know how can I purge the files from a deleted / deactivate user 👍🏻 any chance or is currently not supported by the endpoint ?
