### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nicfab** [Awesome-Technologies/synapse-admin#160]
Following your instructions:
1. I run `cd  synapse-admin`;
2. if I run `yarn install` I receive **No such file or directory: 'install'**
How con I go ahead?

**Comment by awesome-michael** [comment]
Do you have yarn and the other required tools properly installed on your system?

**Comment by nicfab** [comment]
> Do you have yarn and the other required tools properly installed on your system?

I installed yarn with `apt install yarn`.
I don't know if there are other dependencies to install too.

**Comment by awesome-michael** [comment]
It seems that your yarn installation is somehow broken. Try searching for a solution (e.g. here https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install)

**Comment by nicfab** [comment]
> It seems that your yarn installation is somehow broken. Try searching for a solution (e.g. here https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install)

After your suggestion, `yarn install` worked.
Thank you.
Can you tell me how set the nginx reverse proxy to access http://localhost:8080?

**Comment by awesome-michael** [comment]
If you're installing on a remote machine there are plenty of tutorials how to set up nginx as reverse proxy. Just look for something matching your setup.

**Comment by nicfab** [comment]
> If you're installing on a remote machine, there are plenty of tutorials how to set up nginx as reverse proxy. Just look for something matching your setup.

Yes, of course.
However, the app told me that synapse-admin was available on http://localhost:3001 but pointing there nothing was reachable. I opened the ports 3001 and 8080.
Something wrong?

**Comment by nicfab** [comment]
> If you're installing on a remote machine there are plenty of tutorials how to set up nginx as reverse proxy. Just look for something matching your setup.

Sure, thank you.
But http://localhost:8080 where point

> > If you're installing on a remote machine, there are plenty of tutorials how to set up nginx as reverse proxy. Just look for something matching your setup.
> 
> Yes, of course.
> However, the app told me that synapse-admin was available on http://localhost:3001 but pointing there nothing was reachable. I opened ports 3001 and 8080.
> Something wrong?

Now it works.
Thank you very much

**Comment by nicfab** [comment]
Sorry.
It works in development mode.
If I run yarn build it doesn't work.
Where I wrong?
