### ISSUE TITLE
Problem on yarn build

### ISSUE THREAD

**Issue by nicfab** [Awesome-Technologies/synapse-admin#161]
If I run `yarn start`, that system works in development mode and asks me if I want to change the port 3000 already taken by another service. 
I choose yes, and it works on port 3001.
**synapse-admin** works till I stop the service.
If I run `yarn build` at the end, if I point to http://localhost:3001 or http://localhost:3000 nothing is reachable.
Is there anything wrong?

**Comment by dklimpel** [comment]
See also #77

**Comment by nicfab** [comment]
> See also #77

My questions were the same as #77  
The point is not to set the nginx conf file but understand what port that app points to.
Indeed, now it doesn't work on ports: 3000, 3001, 8080.
Is there any settings to modify in package.jason?

**Comment by nicfab** [comment]
> > See also #77
> 
> My questions were the same as #77
> The point is not to set the nginx conf file but understand what port that app points to.
> Indeed, now it doesn't work on ports: 3000, 3001, 8080.
> Is there any settings to modify in package.jason?

I set nginx and now it works properly.
I am sorry for this new issue opened.
Thank you again
