### ISSUE TITLE
New User-ID with default homeserver

### ISSUE THREAD

**Issue by sliwik** [Awesome-Technologies/synapse-admin#163]
Hi,
It is a question rather than issue...

Is it possible to avoid filling in the "@" character and the homeserver when creating a new User-ID ?
In other words: if I enter firstname.lastname as User-ID, it is translated to @firstname.lastname:homeserver.
Thank you.

**Comment by FlorianJSa** [comment]
Hello is anyone working on this proposal otherwise I would look into it

**Comment by dklimpel** [comment]
I think you can work on it. There is no PR at the moment.

**Comment by FlorianJSa** [comment]
Unfortunately I don't have the time to read the code and work on it. Sorry for that
