### ISSUE TITLE
Rooms deletion not work

### ISSUE THREAD

**Issue by panaceya** [Awesome-Technologies/synapse-admin#17]
As i see application send DELETE request to URI, curl example:
```bash
$ curl -X DELETE -H 'Authorization: Bearer <hidden>' 'https://<domain>/_synapse/admin/v1/rooms/!<room_id>:<domain>'
```
But correct is:
```bash
$ curl -v -X POST -d '{ "room_id": "!<room_id>:<domain>"}' --header "Authorization: Bearer <hidden>" 'https://<domain>/_synapse/admin/v1/purge_room'
```

Doc reference: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md

**Comment by awesome-manuel** [comment]
Proper CRUD implementation will be added to v2 admin API in synapse.

**Comment by n1trux** [comment]
until then, can we have a "purge room" feature? :)

**Comment by awesome-manuel** [comment]
See https://github.com/matrix-org/synapse/issues/6425

**Comment by ktpx** [comment]
This does not work.

**Comment by ktpx** [comment]
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
