### ISSUE TITLE
Add <a href> links to users and rooms table for ability to copy url or open detail in new tab

### ISSUE THREAD

**Issue by MurzNN** [Awesome-Technologies/synapse-admin#170]
At now rooms and users, that shown as lists in tables, open details by click - that's ok. But very often I need to copy url, or simply open it in new tab via middle-click.
To implement this feature you can simply add <a href> links to cells in users and rooms table (and to other tables too), if this isn't so hard.

**Comment by dklimpel** [comment]
IMO for this it is necessary to change the design.
Also if you click on a link in this new column, you will be redirected to the defined action in `rowClick`.
`rowClick` has to be disabled and an additional button for the action (edit or show) is required.
