### ISSUE TITLE
Following instructions for nginx gives blank page

### ISSUE THREAD

**Issue by Cknight70** [Awesome-Technologies/synapse-admin#183]
Hi, I am trying to follow the instructions listed in the readme 1)  to set this up via nginx webserver.

This is the process I have done:
downloaded the latest release via https://github.com/Awesome-Technologies/synapse-admin/releases/latest
unpacked the archive resulting in the folder ``synapse-admin-0.8.2`` being created
ran the command ``mv synapse-admin-0.8.2/ /var/www/synapseadmin``
created a nginx site file in sites-available which is as follows:
```
server {
	listen 80;
	listen [::]:80;

	index index.html index.htm;
	
	root /var/www/synapseadmin;

	server_name synapseadmin.mydomain.com;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
}

```
linked to sites-enabled reloaded nginx, and installed certificates via certbot

When I navigate to synapseadmin.mydomain.com it gives me a 403 forbidden error
When I navigate to synapseadmin.mydomain.com/public it gives me an almost blank page with the following console output
![image](https://user-images.githubusercontent.com/28763729/130715707-7e4a9094-cf3a-4764-ac87-d3a7610c56a1.png)

Any assistance would be appreciated

**Comment by dklimpel** [comment]
The readme point 1 is very new. For this part of manual this repo needs a new tagged version. This does not happen until now.
You have to wait for a new version later than 0.8.2. At the moment you can only download the source code and not the files for a deployment with nginx.

You have used the code of version 0.8.2. The readme of this version is https://github.com/Awesome-Technologies/synapse-admin/tree/0.8.2

**Comment by Cknight70** [comment]
That makes sense. I am looking forward to using this project with nginx in the future then, thank you for your help.
