### ISSUE TITLE
Missing version tag on docker hub

### ISSUE THREAD

**Issue by wol-win** [Awesome-Technologies/synapse-admin#186]
Six days ago a new docker image for both amd64 and arm64 has been pushed to docker hub. It is currently tagged with latest, but no specific version tag is associated. Could that be added so that the docker image could be properly integrated into the docker matrix ansible playbook? Thanks

**Comment by skepticalwaves** [comment]
To followup here, 0.8.2 and 0.8.3 are both missing on docerkhub
