### ISSUE TITLE
get error yarn install no such file or directory after git clone

### ISSUE THREAD

**Issue by chrissi55** [Awesome-Technologies/synapse-admin#195]
I git clone the synapse-admin.git to ~/synapse-admin and changed to that directory

cd synapse-admin

In ~/synapse-admin i tried "yarn install" like in step 2 of the Readme.ms but i get the error message see title.

In the cloned dir there is no such file (true so far) but how will i get to run the server now?

Thanks.

System is ZorinOS 16 (based on ubuntu 20.04) with nginx installed.

My vhost is set up and running unter http://localhost (here i can reach the login screen of the Admin UI as well)

**Comment by dklimpel** [comment]
You have to install yarn. E.g. https://linuxize.com/post/how-to-install-yarn-on-ubuntu-20-04/

**Comment by chrissi55** [comment]
I have done this by sudo apt-get install yarn

And yarn --version delivers -> 
0.32+git

yarn upgrade delivers -> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'upgrade'

So is this version dependant?

**Comment by dklimpel** [comment]
See also #160

**Comment by dklimpel** [comment]
My version
```
yarn --version
1.22.10
```

**Comment by chrissi55** [comment]
After uninstalling yarn from the distro repos (ubuntu 20.04) and install of the debian packages yarn install did it's job.
Never the less i decided to use option 1 -> local hosted nginx vhost.

But both methods ended in a "Failed to fetch" message for user, rooms

Only roomdirectory show my public rooms of the homeserver.
My Login is a admin account (admin = 1 in psql database users table)

Should i open a new issue for that - because the login works, but something other seems now to be wrong.

**Comment by dklimpel** [comment]
See also #157 and Readme.md

> You need access to the following endpoints:
/_matrix
/_synapse/admin
See also Synapse administration endpoints

**Comment by chrissi55** [comment]
Thanks!
I have a Reverse Proxy in front of matrix-synapse (as advised by matrix.org) and so i've added

```
location /_synapse/admin {
  		proxy_pass http://IP-OF-MY-MATRIX-SRV:8008;
  		proxy_set_header X-Forwarded-For $remote_addr;
	}
```
to the matrix.conf in /etc/nginx/conf.d of my Reverse Proxy. After login i could fetch data as you described.

Thank you very much for help.
