### ISSUE TITLE
Add some example screenshots

### ISSUE THREAD

**Issue by aaronraimist** [Awesome-Technologies/synapse-admin#20]

**Comment by AnonymousWebHacker** [comment]
![Captura de pantalla (148)](https://user-images.githubusercontent.com/43164089/84733726-56414380-af9f-11ea-8416-ce0fb481e4e2.png)
![Captura de pantalla (149)](https://user-images.githubusercontent.com/43164089/84733730-580b0700-af9f-11ea-915a-2c127cbce45d.png)
![Captura de pantalla (150)](https://user-images.githubusercontent.com/43164089/84733732-593c3400-af9f-11ea-8614-cbe151c13c77.png)
![Captura de pantalla (151)](https://user-images.githubusercontent.com/43164089/84733734-5a6d6100-af9f-11ea-8587-39eaaec6e92f.png)
![Captura de pantalla (152)](https://user-images.githubusercontent.com/43164089/84733735-5b05f780-af9f-11ea-9020-e5abb663819d.png)

**Comment by SuperSandro2000** [comment]
You should probably remove the task bar and the other tabs you have open.

**Comment by AnonymousWebHacker** [comment]
> You should probably remove the task bar and the other tabs you have open.

hahaha does not bother me, I just made a quick capture for you to see what it was about. Thanks for the recommendation

**Comment by awesome-michael** [comment]
Added screenshots in ab709ae
