### ISSUE TITLE
Development really slow...

### ISSUE THREAD

**Issue by Fail-Unsafe** [Awesome-Technologies/synapse-admin#203]
I probably come of as rude but the development of this important app in the Matrix universe is really painfully slow. Maybe you want to hand over development to folks who have more time at their hands, i.e. maybe someone can fork this repository and merge the numerous pull requests...

**Comment by awesome-michael** [comment]
Thank you for your feedback. We as well feel that we could be faster and try to push for quicker turnaround times for bug and feature requests. As any open source project we also rely on the community to help us move faster. Picking up open issues is very helpful and very much appreciated.
We agree that this is important and this is why we always are reviewing pull requests and running additional tests before we publish new code. We are sorry that this leads to delays in the development.
