### ISSUE TITLE
Failed to fetch when trying to log in to synapse-admin

### ISSUE THREAD

**Issue by infocilla** [Awesome-Technologies/synapse-admin#204]
Hi,

Despite having already tried what the issues #76 #88 #157 #18 mentionned, I'm not able to connect to my synapse admin interface and I've got the "Failed to fetch" error. The Synapse version does not even appear on the login page.

- Synapse version: 1.46
- Synapse-Admin version: 0.8.3
- Server: Debian 10 / Apache 2.4.38

Here is my apache vhost config:

```
<VirtualHost *:80>
    ServerName matrix-admin.example.com

DocumentRoot /var/www/admin-matrix

        <Directory /var/www/admin-matrix>
        Options Indexes FollowSymLinks
        AllowOverride All
        </Directory>

Redirect permanent / https://matrix-admin.example.com
</VirtualHost>


<VirtualHost *:443>
    SSLEngine on
    ServerName matrix-admin.example.com

DocumentRoot /var/www/admin-matrix
        <Directory /var/www/admin-matrix>
        Options Indexes FollowSymLinks
        AllowOverride All
        </Directory>

    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix

    ProxyPass /_synapse http://127.0.0.1:8008/_synapse nocanon
    ProxyPassReverse /_synapse http://127.0.0.1:8008/_synapse
    #ProxyPass /_synapse/admin http://127.0.0.1:8008/_synapse/admin nocanon
    #ProxyPassReverse /_synapse/admin http://127.0.0.1:8008/_synapse/admin

SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example. com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

I don't understand what is wrong or doesn't work
Should I enable proxypass from /_synapse/admin to local synapse server ?
Should I add some Proxy stuff ?
Is the `nocanon` stuff required for ProxyPass directive ?

I'm lost...

Thanks a lot for your help !
Infocilla

**Comment by BBaoVanC** [comment]
> Should I enable proxypass from /_synapse/admin to local synapse server ?

Yes, since it allows the admin api which is required for pretty much everything synapse admin does

Not sure about the other two questions because I don't know apache, but I would try it just uncommenting /_synapse/admin first

**Comment by infocilla** [comment]
Hi and thank you @BBaoVanC 
Uncommenting /_synapse/admin gives me the same error

**Comment by infocilla** [comment]
Looking at the browser console, I can see some errors about CORS policy.
I didn't find any complete tutorial about how to enable CORS policy on a synapse server... (added some header stuff in my Apache virtualhost but with no effect, I don't know how to enable it at the synapse server level itself)
Any help would be much appreciated !

**Comment by dklimpel** [comment]
The simplest solution ist to use the same hostname for synapse and synapse-admin.

**Comment by infocilla** [comment]
Thanks @dklimpel 
I moved everything under the same hostname and it works.
I'm still open to k now how to implement CORS policy, because I still don't understand the documentation.
