### ISSUE TITLE
Deleting media doesn't work in Firefox unless you manually fill in timestamp

### ISSUE THREAD

**Issue by aaronraimist** [Awesome-Technologies/synapse-admin#215]
A user tried to delete media by only filling in a date. This produced an error with no information about why.
![image](https://user-images.githubusercontent.com/5855073/146212187-ee080fa8-2d76-4a67-8832-d66336593be5.png)

In the browser console there was

```
errcode	"M_INVALID_PARAM"
error	"Query parameter 'before_ts' must be an integer"
```

which seems to be because Synapse admin sends an invalid `before_ts` if you don't manually fill in the time in addition to the date.

I would propose that synapse-admin defaults to 00:00 if the time is left unset or alternatively prompts you to set the time.

See original report: https://matrix.to/#/!cNSQwPqhHKkIZdBnvt:devture.com/$DYP1cT3CX2DBElZ_0bbXHbY4fMcikKmt64hquZcS2I0?via=devture.com&via=matrix.org&via=maunium.net

**Comment by dklimpel** [comment]
> i was using firefox,  i switch to chromium which automatically detects and fills the hour minute, and now it works

https://matrix.to/#/!cNSQwPqhHKkIZdBnvt:devture.com/$TBRb3yZPAz2_qzo1IRVM0lue8YTgZpQxqT5J_19uvSY?via=devture.com&via=matrix.org&via=maunium.net

**Comment by dklimpel** [comment]
The DateTimePicker is missing here for Safari and Firefox.
See also
- https://marmelab.com/react-admin/Inputs.html#datetimeinput
- https://github.com/marmelab/react-admin/issues/2685

**Comment by awesome-manuel** [comment]
Seems to be fixed.
