### ISSUE TITLE
Reactivated users are immune to system messages

### ISSUE THREAD

**Issue by Shayshon** [Awesome-Technologies/synapse-admin#218]
Users who are deleted then later reactivated are immune to system messages/notices.

**Comment by dklimpel** [comment]
IMO if this is a bug, this is a bug in Synapse.
I have done a test and cannot reproduce it.

Do you have more information? Server-Version, steps to reproduce, etc.

**Comment by Shayshon** [comment]
> IMO if this is a bug, this is a bug in Synapse.
> I have done a test and cannot reproduce it.
> 
> Do you have more information? Server-Version, steps to reproduce, etc.

Hi! I'm sorry, I made a bit of a typo. From what I've seen, users who are deleted and later re-enabled don't seem to receive these messages. Although I do believe it may still be a bug. My server version is 1.49.2.

Steps to reproduce:
1. Delete a user
2. Re-enable the deleted user
3. Attempt to send system message
4. See result

**Comment by TildeSlashC0re** [comment]
I think I've run across a similar bug where I'd get a `403 "POST /_synapse/admin/v1/send_server_notice` ... after restarting synapse I was able to send that user a server notice again. 

Certainly a synapse issue.

**Comment by Shayshon** [comment]
> I think I've run across a similar bug where I'd get a `403 "POST /_synapse/admin/v1/send_server_notice` ... after restarting synapse I was able to send that user a server notice again. (`HTTPStatus.OK "POST /_synapse/admin/v1/send_server_notice`)
> 
> Certainly a synapse issue.

I see, should I create an issue in the synapse github?
