### ISSUE TITLE
Can't install synapse-admin with docker container

### ISSUE THREAD

**Issue by CLU91** [Awesome-Technologies/synapse-admin#246]
Hello,

i tried to install synapse-admin via the command: docker run -p 8080:80 awesometechnologies/synapse-admin

The installation process starts as expected but stops at "start worker process 34" and is not doing anything from there on. Quick information about my setup. I am using Oracle Free Cloud. They have Arm based free VPS. I was able to run Matrix Synapse in a Docker Container. Now i tried to install a admin gui to have better overview about the users, rooms, etc.

best regards CLU

**Comment by awesome-michael** [comment]
Could you access synapse-admin on port 8080 when the container was started?
You don't have to install synapse-admin, just run the container like you do with synapse.

**Comment by CLU91** [comment]
No nothing is happening on Port 8080. The port is active in both firewall (Oracle and local ufw).  Im quite new to docker... having hard time to figure out how to simply run the container

**Comment by awesome-michael** [comment]
Seems to be a network problem, not something synapse-admin is responsible for. Try to search some information about docker containers itself. If there is a problem with synapse-admin feel free to reopen the issue.
