### ISSUE TITLE
Sorting any tables should use stable_sort

### ISSUE THREAD

**Issue by Samonitari** [Awesome-Technologies/synapse-admin#252]
Thanks for the work!

I am not versed in JavaScript, but I guess there *is* a stable sort in the basic libs.
**Any** table UI that provides sorting by columns should use stable_sort (in any application, TBH).

Example scenario - I'd like to see the most recent-versioned rooms that are encrypted. To do this you (order is not relevant in this case):
1. First sort by room versions
2. Then sort by E2EE status

Current result: rooms are listed by E2EE status, but room version ordering in the encrypted results on top are not kept.

**Comment by awesome-manuel** [comment]
Sorting is done by the server. So we depend on the admin API from synapse.
