### ISSUE TITLE
How to undo "erase user data"? 

### ISSUE THREAD

**Issue by KeenMaron** [Awesome-Technologies/synapse-admin#260]
I just accidentally deleted my user with the "erase user data" thinking it will delete only my sent files. Is there an possible way to undo this process?

**Comment by awesome-michael** [comment]
Unfortunately I don't think there is a way to undo this. Although this is rather a question for synapse itself since synapse-admin just uses the API synapse provides.

**Comment by KeenMaron** [comment]
Ok, thank you for the reply. It is a little bit amusing, that I can delete myself while logged in as administrator and then being locked out.

**Comment by awesome-michael** [comment]
Yeah thats really a bit strange. Maybe you should file an issue for that over at https://github.com/matrix-org/synapse
