### ISSUE TITLE
At user creation chinese usernames are not valid

### ISSUE THREAD

**Issue by thepra** [Awesome-Technologies/synapse-admin#274]
![immagine](https://user-images.githubusercontent.com/7032509/179353065-018c1730-b0b7-42da-b659-f803c6eeceb8.png)
as in the picture, it does seem that there's a validation restriction which is too strict and does accept non-latic characters.
Can it be fixed?

**Comment by Twi1ightSparkle** [comment]
Chinese characters are not allowed by the Matrix spec: https://spec.matrix.org/v1.7/appendices/#user-identifiers

**Comment by thepra** [comment]
So, until spec change, unicode can't be of use. Is there a way and place to submit a spec change?

**Comment by Twi1ightSparkle** [comment]
See https://spec.matrix.org/proposals/
For further spec questions, I recommend you ask in https://matrix.to/#/#matrix-spec:matrix.org
That said, I don't think we'd want to extend the localpart character set. But I'm not on the spec team, so not my call.
