### ISSUE TITLE
synapse-admin not working with synapse 1.64

### ISSUE THREAD

**Issue by versus167** [Awesome-Technologies/synapse-admin#281]
Since upgrade from synapse 1.61 to 1.64 i got this error after login to synapse-admin: 
![Bildschirmfoto von 2022-08-05 16-56-57](https://user-images.githubusercontent.com/3191327/183104338-a0f29fdd-290b-42a7-9e9f-081ba21c7a47.png)

docker-compose.yaml:

synapse-admin:                                                                                                                                                   
    container_name: synapse-admin                                                                                                                                  
    hostname: synapse-admin                                                                                                                                        
    build:                                                                                                                                                         
      context: https://github.com/Awesome-Technologies/synapse-admin.git                                                                                           
      # args:                                                                                                                                                      
      #   - NODE_OPTIONS="--max_old_space_size=1024"                                                                                                               
    ports:                                                                                                                                                         
      - "8080:80"                                                                                                                                                  
    restart: unless-stopped      

and synapse from docker.io/matrixdotorg/synapse:latest

Where can I look what happen?!

**Comment by awesome-michael** [comment]
Having a look at the developer console of your browser could provide some useful information.
The "Network Error" implies that synapse-admin could not connect to the synapse api.

**Comment by mightymop** [comment]
i had the same error... it was cors related
try to login via http not https (when setting the homeserver url at login)

**Comment by versus167** [comment]
Okay, it was no problem with synapse-admin -> I tried my homeserver-url with a false port....
