### ISSUE TITLE
Trying to log in gives "a.well_known is undefined"

### ISSUE THREAD

**Issue by ltning** [Awesome-Technologies/synapse-admin#29]
I have synapse-admin running, and synapse as a homeserver (for now). I am publishing .well-known/matrix/server, but that does not seem to be the problem.

**Comment by mkszuba** [comment]
Is this _really_ related? I have just encountered the same problem, using a freshly pulled Docker image, and none of the server logs indicate any attempts of accessing well-known files, which do exist and can be accessed via https://base.domain/ . I see the (successful, as attested to by the fact a new user session is registered) log-in attempt and that's it.

**Comment by awesome-michael** [comment]
Do you publish .well-known/matrix/client as well? I think the server file is used for federation and we need the URL of the client API.

**Comment by dklimpel** [comment]
IMHO is the URL of the client API not the sme like for admin API, automatically. For security reason it is important to use different IPs or URLs. Client API over internet and admin API over intranet or VPN.

**Comment by awesome-manuel** [comment]
Fixed in 2d0ce50444e328eb2a678306294628d7423e1e79
