### ISSUE TITLE
Admin API - Command Not Found

### ISSUE THREAD

**Issue by belascoain** [Awesome-Technologies/synapse-admin#293]
Hi,

I'm trying to use admin API in our Matrix Server using curl command, but all commands that I use give the same result:

Error 404

I can use Client API withount problems.

For example:

I can create a new room:

curl -XPOST -d '{"room_alias_name":"test"}' "https://MY_SERVER/_matrix/**client**/r0/createRoom**********

But I can't delete it

curl -X "DELETE" "https://MY_SERVER/_matrix/**admin**/v1/rooms/test"

It's like my Admin API isn't where it should, or it wasn't enabled

How can I check that admin API is enable?

Regards

**Comment by dklimpel** [comment]
> curl -X "DELETE" "https://MY_SERVER/_matrix/**admin**/v1/rooms/test"

You uses the a wrong URL.
See: https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#version-2-new-version

`DELETE /_synapse/admin/v2/rooms/<room_id>`

**Comment by belascoain** [comment]
Sorry. But it doesn't work for me.

I've tried to get info about my user

# curl -XGET "https://MYSERVER/_matrix/admin/v2/users/@MY_USER"

This is the response:

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>

**Comment by dklimpel** [comment]
Please read the [docs](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html).

`GET /_synapse/admin/v2/users/<user_id>`

The Admin API URLs start with **/_synapse/admin/** an NOT **/_matrix/admin/**!

**Comment by dklimpel** [comment]
Do you have added `/_synapse/admin` to your reverse proxy configuration?
Info: https://matrix-org.github.io/synapse/latest/reverse_proxy.html#synapse-administration-endpoints

Related to: https://github.com/Awesome-Technologies/synapse-admin/issues/88#issuecomment-1068838894

**Comment by dklimpel** [comment]
IMO this issue is stale and fixed.
