### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by floviolleau** [Awesome-Technologies/synapse-admin#303]
Hi,

Thanks a lot for this amazing project and allowing us to administrate our self-hosted servers.

Do you have plans for a new release?

Thanks a lot!

**Comment by awesome-michael** [comment]
Hi,

Thanks for your appreciation.
Unfortunately we are experiencing a high load on our developers for quite a long time now. But we try to build a new release within the next days.

**Comment by floviolleau** [comment]
Hi,

Would be nice to have quick change log next time

Thanks ❤️
