### ISSUE TITLE
0.8.6 makes it harder to serve at a different prefix

### ISSUE THREAD

**Issue by spantaleev** [Awesome-Technologies/synapse-admin#322]
0.8.6 hardcodes `ARG PUBLIC_URL=/` in the `Dockerfile`, so the prebuilt container images expect to be served at `/`. I doubt most people would like to dedicate a whole domain to synapse-admin.

Serving it under a prefix like `/synapse-admin` (like we do at [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)) either requires rebuilding the container image (slow & difficult for most people) or a more complex reverse-proxying configuration.

If reverse-proxying from nginx, the following additional configuration may help:

```nginx
sub_filter_once off;
sub_filter "/static/" "/synapse-admin/static/";
sub_filter "/favicon.ico" "/synapse-admin/favicon.ico";
sub_filter "/manifest.json" "/synapse-admin/manifest.json";
```

-----

Also.. this was a nasty breaking change to introduce in a minor release (0.8.5 -> 0.8.6). There's no changelog / release notes to mention it either, so this whole situation is very unfriendly to people using this project.

**Comment by dklimpel** [comment]
This is probably an oversight in #266 for default docker image.

Before that it was the default directory  `.`.
https://github.com/Awesome-Technologies/synapse-admin/blob/3276a9b6ed3060f9ca1630b67367004d4e93fcc2/package.json#L7

Now it is `/`
https://github.com/Awesome-Technologies/synapse-admin/blob/3276a9b6ed3060f9ca1630b67367004d4e93fcc2/Dockerfile#L4

**Comment by awesome-michael** [comment]
Sorry for that and thanks for creating the issue. Will have a look at it

**Comment by mcnesium** [comment]
Here is a workaround if you are [running your own webserver](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md) using Apache: just add this config above [these lines](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/examples/apache/matrix-synapse.conf#L50-L56):

    # working around this bug https://github.com/Awesome-Technologies/synapse-admin/issues/322
    ProxyPass /static http://127.0.0.1:8766/static
    ProxyPassReverse /static http://127.0.0.1:8766/static
    ProxyPass /favicon.ico http://127.0.0.1:8766/favicon.ico
    ProxyPassReverse /favicon.ico http://127.0.0.1:8766/favicon.ico
    ProxyPass /manifest.json http://127.0.0.1:8766/manifest.json
    ProxyPassReverse /manifest.json http://127.0.0.1:8766/manifest.json

**Comment by dud1337** [comment]
If there is a workaround with traefik it is 2jank5me to figure out. I agree that leaving the base as `.` would be better design. And - thank you for your work on this useful project.

**Comment by dklimpel** [comment]
There is a patch (in awesometechnologies/synapse-admin:latest): 9b43d41040b79cc8ad240dbadc66098bc8231c2b

Is this issue resolved?

**Comment by awesome-michael** [comment]
I tested a few things, trying to make the public_url configurable via environment variables. Unfortunately nothing worked. So I decided to just remove the fixed public_url for now.
I just have to build a release for it, then the issue should be resolved. If there is any issue left feel free to open another Github  issue.
