### ISSUE TITLE
Feature:  Include a default room for new user

### ISSUE THREAD

**Issue by sm2x** [Awesome-Technologies/synapse-admin#34]
During the creation of a new user, it would be nice if you can assign a default room that when the user logins the first time, the user will auto-join to the default room.  This similar feature can be configured on the homeserver.yaml but it is for every user.

Also, a view that can show the list of rooms a user is a member is very helpful.

**Comment by rubo77** [comment]
This is a creature, that you should ask in the synapse repository. I am pretty sure the request was made there already, so please search existing issue first

**Comment by dklimpel** [comment]
This admin UI can only represent an UI of the functions of synapse admin api. 
All functions of synapse admin api you can find here: https://github.com/matrix-org/synapse/tree/master/docs/admin_api

**Comment by awesome-manuel** [comment]
You can configure this using the `homeserver.yaml`.
```
# Users who register on this homeserver will automatically be joined
# to these rooms
#
#auto_join_rooms:
#  - "#example:example.com"
```
