### ISSUE TITLE
error	"Unrecognized request"

### ISSUE THREAD

**Issue by onlineapps-cloud** [Awesome-Technologies/synapse-admin#351]
hi, i have this error when i connecting to dendrite (https://github.com/matrix-org/dendrite)
on dendrite say: `we have 100% server-server parity with Synapse` so problem is not in dendride, maybe some obsolete commands is using  in requests
![image](https://user-images.githubusercontent.com/69077240/226171570-862bf34c-8cc0-4b1f-ba08-ab631941c74b.png)

i use synapse-admin in docker image (https://hub.docker.com/r/awesometechnologies/synapse-admin)

**Comment by dklimpel** [comment]
Administration APIs are specific for servers and not part of the matrix protocol/ specification.

The supported admin API is there: https://matrix-org.github.io/dendrite/administration/adminapi

**Comment by dklimpel** [comment]
> As of January 2023, we have 100% server-server parity with Synapse, and the client-server parity is at 93% , though check CI for the latest numbers. 

"Server-Server parity" means the federation API between two servers. It does not mean that the server has all the same APIs implemented.

**Comment by onlineapps-cloud** [comment]
ok, i will ask in dendride issues about adminapi.
