### ISSUE TITLE
Show members in room details

### ISSUE THREAD

**Issue by sm2x** [Awesome-Technologies/synapse-admin#36]
Is there a way to show the members of a Room, and then you can kick selected users from the Room?

**Comment by awesome-manuel** [comment]
This needs https://github.com/matrix-org/synapse/pull/7317

**Comment by awesome-manuel** [comment]
Sorry, https://github.com/matrix-org/synapse/pull/7317 was not enough, we need a separate endpoint for room members.

**Comment by awesome-michael** [comment]
Will be available when https://github.com/matrix-org/synapse/pull/7842/ got merged

**Comment by twouters** [comment]
The room members endpoint should be available in 1.18.0, right?

**Comment by awesome-michael** [comment]
Yes, the endpoint is available in 1.18.0. Now we need to adapt the data provider to use this endpoint.

**Comment by awesome-michael** [comment]
Members are now (v0.5.0) shown in a tab in room details
