### ISSUE TITLE
Make it more difficult to accidentally delete accounts

### ISSUE THREAD

**Issue by erebion** [Awesome-Technologies/synapse-admin#365]
Hello,

this just happened to me:

I searched for "bot" to delete one of my bridge accounts for a bridge I turned off.
The search was slow apparently... I clicked the result, nothing happened, I clicked a second time.

While I was doing that the list of search results updated, I selected the wrong user and then continued to do a "GDPR erase" of the wrong user. In the end I happened to delete my own account instead.

Please add something like "Please confirm deleting data by typing out the username" and then if it does not match cancel the action. :D 

Now going to restore my backup...

**Comment by awesome-manuel** [comment]
The current confirmation dialog is enough. This is a tool for experienced users.

**Comment by erebion** [comment]
> This is a tool for experienced users.

No reason at all to make it easier than necessary to cause damage.
