### ISSUE TITLE
SSO administration only shows second account

### ISSUE THREAD

**Issue by gabrc52** [Awesome-Technologies/synapse-admin#373]
![image](https://github.com/Awesome-Technologies/synapse-admin/assets/24363938/6817e7a0-1281-4862-b1a1-30444e67ed4e)

Only after refreshing the tab do both entries appear.

If you remove the first entry, the animation comes out of the second entry. 

I don't have React experience, but based on other frontends, maybe some keys/IDs are needed.

**Comment by dklimpel** [comment]
Related to:
- #362
- #363

**Comment by gabrc52** [comment]
Yeah seems like the same bug

**Comment by gabrc52** [comment]
Hmm I can't reproduce, maybe it's fixed already
