### ISSUE TITLE
"Your session has ended, please reconnect."

### ISSUE THREAD

**Issue by eMPee584** [Awesome-Technologies/synapse-admin#38]
I did start this container via
`docker run -it --rm --publish 28838:80 --link matrix-synapse --net matrix awesometechnologies/synapse-admin`
and wanted to access it through an SSH tunnel.. unexpectedly (because no docs; thought it might notice that it's ON the HS, even attached to it) it asked for a homeserver URL. Ok so I put in the requested information and for a blink, the GUI showed up, then it went back to the login screen with "Your session has ended, please reconnect.". Nothing was logged, except the initial HTTP gets.

**Comment by awesome-manuel** [comment]
Should be fixed in latest master. Please try again.

**Comment by awesome-michael** [comment]
Since this is should be fixed a month ago I'll close this one. Please reopen if the problem persists.

**Comment by echtniels** [comment]
Running synapse-admin behind Traefik reverse proxy gives me the exact same results. User, password & homeserver are validated, the main screen opens (with info ghosted and a spinner top-right) and then returns me to the logon screen with the message "Your session has ended, please reconnect".

- No info shown on the docker logs
- Tried :latest and a few older releases
- Entering a random user or password fails so authentication DOES happen
- synapse-admin and synapse are both exposed on port 443 on subdomains of the same domain
