### ISSUE TITLE
Error when running via yarn

### ISSUE THREAD

**Issue by snex** [Awesome-Technologies/synapse-admin#387]
The webpage is completely blank and the following error displays in the js console:

```
Uncaught Error: Invariant failed: You should not use <Switch> outside a <Router>
    at invariant (tiny-invariant.esm.js:12:1)
    at Switch.js:17:1
    at updateContextConsumer (react-dom.development.js:18747:1)
    at beginWork (react-dom.development.js:19114:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
invariant @ tiny-invariant.esm.js:12
(anonymous) @ Switch.js:17
updateContextConsumer @ react-dom.development.js:18747
beginWork @ react-dom.development.js:19114
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./src/index.js @ index.js:5
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
```

**Comment by dklimpel** [comment]
On my workstation it works:
```sh
~/synapse-admin$ yarn --version
1.22.19
~/synapse-admin$ node --version
v18.17.1

~/synapse-admin$ yarn start
yarn run v1.22.19
warning ../package.json: No license field                                                                                                                                                                  
$ REACT_APP_VERSION=$(git describe --tags) react-scripts start
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
(node:1322063) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1322063) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Compiled successfully!

You can now view synapse-admin in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://ip3000

Note that the development build is not optimized.
To create a production build, use yarn build.

webpack compiled successfully

```

**Comment by snex** [comment]
Hi, thanks for your reply. I get the same output on the CLI, but the error I am reporting is happening inside the browser.

**Comment by dklimpel** [comment]
I get the login screen displayed.

You have exactly the same yarn and node version?

**Comment by snex** [comment]
Not exactly the same:

```
> yarn --version
1.22.19
> node --version
v20.8.0
```

Does this only work with node18 specifically? If so, that's bizarre. It also seems to be an error on the client side so not sure why the node version would even matter. The page is being served, it just doesn't render.

**Comment by dklimpel** [comment]
It works with node lts. The last node lts is node v18.
It may be that it is not compatible with node 20

**Comment by Riven-Spell** [comment]
> On my workstation it works:
> 
> ```shell
> ~/synapse-admin$ yarn --version
> 1.22.19
> ~/synapse-admin$ node --version
> v18.17.1
> 
> ~/synapse-admin$ yarn start
> yarn run v1.22.19
> warning ../package.json: No license field                                                                                                                                                                  
> $ REACT_APP_VERSION=$(git describe --tags) react-scripts start
> Browserslist: caniuse-lite is outdated. Please run:
>   npx update-browserslist-db@latest
>   Why you should do it regularly: https://github.com/browserslist/update-db#readme
> (node:1322063) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> (node:1322063) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
> Starting the development server...
> 
> Compiled successfully!
> 
> You can now view synapse-admin in the browser.
> 
>   Local:            http://localhost:3000
>   On Your Network:  http://ip3000
> 
> Note that the development build is not optimized.
> To create a production build, use yarn build.
> 
> webpack compiled successfully
> ```

Used *exactly* this version and built, worked fine

**Comment by snex** [comment]
> Used _exactly_ this version and built, worked fine

Do you see the error when using other versions? Because this is starting to sound like a giant waste of my time. If you do see the error on other versions, then let's get this fixed. "Use older versions of software" is a bad solution.

**Comment by Riven-Spell** [comment]
> > Used _exactly_ this version and built, worked fine
> 
> Do you see the error when using other versions? Because this is starting to sound like a giant waste of my time. If you do see the error on other versions, then let's get this fixed. "Use older versions of software" is a bad solution.

I agree. I retried after a `yarn build` with 20.x and it's working. Why? I'm not exactly sure.

**Comment by dklimpel** [comment]
I did a test with `node v20.8.0`, without problems.

**Comment by dklimpel** [comment]
Presumably this is no longer the case with react admin 4 and Synapse Admin v0.9.

**Comment by snex** [comment]
The page does load now. Thanks for the followup.
