### ISSUE TITLE
Bad Request with the Import Feature

### ISSUE THREAD

**Issue by BxptisteM** [Awesome-Technologies/synapse-admin#406]
Hi,
I'm trying to set up a chat system using synapse and element as a web client, I need to use an SSO server for authentication and make sure my users are "pre-registered" in synapse, so I was going to use synapse-admin's CSV table import functionality but I have a problem when installing synapse-admin to my project, when I try to import a CSV table of users, I get an error "For entry 1: Bad Request".

![image](https://github.com/Awesome-Technologies/synapse-admin/assets/114676002/64eb7ee0-36de-4f9e-85e7-39d252befc64)

This happens all the time, even with the example file.
How can I fix this ? (I'm using the Docker image)

PS: I need to import more than 130,000 users, will the feature support this ?

Thanks

**Comment by phk-nord** [comment]
I just had to deal with this myself, it's seems the example .csv is wrong
while it shows:
```csv
id,displayname,password,is_guest,admin,deactivated
@testuser22:example.org,Jane Doe,secretpassword,false,true,false
```
the manual registration process shows you an error message that you shouldn't use either @ or _:synapse.domain_
so this csv format worked for me with synapse-admin v0.8.5 and synapse v1.90. I haven't notice an update was out already for synapse-admin so I haven't tried that version yet.
 ```csv
id,displayname,password,is_guest,admin,deactivated
testuser22,Jane Doe,secretpassword,false,true,false
```
Do keep in mind that with that many users you will most likely run into a [rate limiting](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html?highlight=limit#rc_registration) of synapse if you didn't adjust it in your homeserver.yaml

Note: it's interesting to see that using the wrong example.csv succeeds in simulation import

**Comment by BxptisteM** [comment]
Thanks for your answers ! :rocket:
