### ISSUE TITLE
Search Users Function

### ISSUE THREAD

**Issue by sm2x** [Awesome-Technologies/synapse-admin#42]
Is it possible to have a search function to find users based on ID or any part of Display Name?

**Comment by awesome-manuel** [comment]
We first need to have https://github.com/matrix-org/synapse/pull/7377 in synapse.

**Comment by sm2x** [comment]
awesome, thank you manuel

**Comment by pascal-klesse** [comment]
Hi all, really cool and useful project. Saw that the merge request was merged. When will the feature be processed?

**Comment by dklimpel** [comment]
I think it is merged already: https://github.com/Awesome-Technologies/synapse-admin/commit/3d7c0bf67f2112052fe90ed629ac68852debaf28
