### ISSUE TITLE
Slashes in user IDs are not encoded and users not viewable

### ISSUE THREAD

**Issue by sebix** [Awesome-Technologies/synapse-admin#443]
If the user ID contains slashes, e.g. `@foo/bar:server`, the UI does attempt to request the addresses
https://example.com/_synapse/admin/v2/users/@foo/bar:matrix.fez-berlin.de/devices?dir=b&from=0&limit=25&order_by=id
etc., which of course return an error 404.
`/` in the User IDs must be replaced by `%2F`.
Possibly other characters are affected as well.

**Comment by awesome-manuel** [comment]
Is there a final spec what is allowed in an MXID?

**Comment by sebix** [comment]
https://spec.matrix.org/v1.9/appendices/#identifier-grammar says 
> Identifiers must start with one of the characters [a-z], and be entirely composed of the characters [a-z], [0-9], -, _ and ..

But synapse at least allows `/`, so that can't be the full truth

**Comment by awesome-manuel** [comment]
In the latest version I can create and view such users.

**Comment by sebix** [comment]
Thanks, I'll retest it today. Actually, I wanted to do that yesterday, but, yeah, other stuff interrupted.

**Comment by sebix** [comment]
I confirm this issue is fixed in the last version
