### ISSUE TITLE
Bad Request: undefined when trying to modify a user

### ISSUE THREAD

**Issue by gabrc52** [Awesome-Technologies/synapse-admin#461]
I'm trying to modify a user on https://awesome-technologies.github.io/synapse-admin/#/users

but I am getting

![image](https://github.com/Awesome-Technologies/synapse-admin/assets/24363938/e44c772f-2c0d-4023-b19a-207c2b0d0170)

The network tab says it tried putting undefined as the mxid

![image](https://github.com/Awesome-Technologies/synapse-admin/assets/24363938/fb126b8e-a5fd-476a-97dc-e7f7eda4329f)

**Comment by dklimpel** [comment]
IMO this is a bug in v0.9.0. It should be working again by now with totay commits.
