### ISSUE TITLE
RFC: Migrate to Vite.js

### ISSUE THREAD

**Issue by awesome-manuel** [Awesome-Technologies/synapse-admin#464]
There are two vulnerabilities caused by `react-scripts` that probably will never be fixed:
- https://github.com/Awesome-Technologies/synapse-admin/security/dependabot/1
- https://github.com/Awesome-Technologies/synapse-admin/security/dependabot/58

Suggestion is to abandon the old `react-scripts` and migrate to `vitejs`.

Any comments? @dklimpel

**Comment by dklimpel** [comment]
The security links are not public. I cannot see it (`404`).
I have no preference to this topic.

It seems not to be very complex: https://www.robinwieruch.de/vite-create-react-app/

**Comment by awesome-manuel** [comment]
The migration should also adress
- #284
- #335
