### ISSUE TITLE
how to install? 

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Awesome-Technologies/synapse-admin#48]
I don't know how to install it, could you explain requirements and how to install it?

**Comment by toshanmugaraj** [comment]
https://hub.docker.com/r/awesometechnologies/synapse-admin

**Comment by AnonymousWebHacker** [comment]
> 
> 
> https://hub.docker.com/r/awesometechnologies/synapse-admin

403 Forbidden
Since Docker is a US company, we must comply with US export control regulations. In an effort to comply with these, we now block all IP addresses that are located in Cuba, Iran, North Korea, Republic of Crimea, Sudan, and Syria. If you are not in one of these cities, countries, or regions and are blocked, please reach out to https://support.docker.com 

Tanks any way

**Comment by SuperSandro2000** [comment]
```shell
git clone https://github.com/Awesome-Technologies/synapse-admin.git
cd synapse-admin
docker build . -t synapse-admin
docker run ... synapse-admin
```

**Comment by AnonymousWebHacker** [comment]
> ```shell
> git clone https://github.com/Awesome-Technologies/synapse-admin.git
> cd synapse-admin
> yarn install
> yarn start 
> ```
It worked like this, something wrong on this road? something wrong?

**Comment by awesome-michael** [comment]
If you want to run it locally your last attempt (which is also described in the readme) is the way to go
