### ISSUE TITLE
URL has to start with 'http://' or 'https://'

### ISSUE THREAD

**Issue by emoxam** [Awesome-Technologies/synapse-admin#480]
My homeserver field filled in tight. But when i try to login a get an error
`URL has to start with 'http://' or 'https://'`
But it acually starts with https://

![image](https://github.com/Awesome-Technologies/synapse-admin/assets/3593601/8e1bbe73-f41e-4f9e-b1b5-38fe5a58d5e1)

**Comment by dklimpel** [comment]
Try to remove the quotation marks `"` -> `https://matrix.integris.ru`
