### ISSUE TITLE
Encryption Support?

### ISSUE THREAD

**Issue by rwjack** [Awesome-Technologies/synapse-admin#495]
Currently, I have an unverified session showing on my devices list, and it is because SA does not support encryption:

![image](https://github.com/Awesome-Technologies/synapse-admin/assets/59068073/db081cdc-05ac-4a3a-af34-88993b36e3de)

Is it even posible for SA to support encryption?

**Comment by awesome-manuel** [comment]
SA will not become a chat client. So since there is no need to read and write encrypted messages, it will most likely not implement end2end encryption.

It it advisable to use a different account for administrative purposes with different credentials from your normal account.
