### ISSUE TITLE
EraseData Option

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Awesome-Technologies/synapse-admin#50]
I think it would be very good, that they would implement, room, users and options (Data). 
-Users          -Rooms          -Data
# Where possible file deletion can be chosen [timestap or media_size + mtime]
1 - By TIMESTAP  or /  2 - Purge Local/Remote Media
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst

something like this ;)
 
> ```shell 
> find /var/lib/matrix-synapse/media/ -type f -size +5M -mtime +120 -exec rm  -r {} \;
> ``` 
# Erase size >5MB, older than 120 days (example)

this would be possible?  Thank you very much for your work.

**Comment by awesome-manuel** [comment]
We need some more admin endpoints from Synapse in order to make this work, but sure we're on it.
