### ISSUE TITLE
Don't know how to set the public URL

### ISSUE THREAD

**Issue by paulvt** [Awesome-Technologies/synapse-admin#512]
The [release notes of 0.10.0](https://github.com/Awesome-Technologies/synapse-admin/releases/tag/0.10.0) mention that the public URL needs to be set using `config.json`. It points to the README but the README only explains how to restrict base URLs. As a result, I have no idea how to set the public URL.

My deployment runs under `https://matrix.domain.tld/synapse-admin` and it tries to get the JSON at `/assets/foobar.js` now, which obviously does not work.

**Comment by awesome-manuel** [comment]
The [README.md](https://github.com/Awesome-Technologies/synapse-admin/blob/0.10.0/README.md#serving-synapse-admin-on-a-different-path) now even contains a whole chapter about this topic.

If you really really need to do this without a reverse proxy, then run `yarn build --base=/synapse-admin`. See https://vitejs.dev/guide/build.html#public-base-path for more information.

**Comment by LelieL91** [comment]
> The [README.md](https://github.com/Awesome-Technologies/synapse-admin/blob/0.10.0/README.md#serving-synapse-admin-on-a-different-path) now even contains a whole chapter about this topic.
> 
> If you really really need to do this without a reverse proxy, then run `yarn build --base=/synapse-admin`. See https://vitejs.dev/guide/build.html#public-base-path for more information.

Hi, I'm having the same issue as @paulvt, and still can't find the related part on the README.md. About the base_url, there is only the "traefik way" and nothing about the config.json.
My deployment is running on NGINX reverse proxy, it was working until 0.9.4 update, now my subpath is not recognised and the main domain is used leading to a wrong path to "/assets/index-DE-VvRNO.js".

**Comment by awesome-manuel** [comment]
To quote the README.md: "We do not support directly changing the path where Synapse-Admin is served."

The path prefix cannot be changed via the `config.json` since this file itself has to be loaded from the prefix. So a dynamic configuration is not possible.

For NGINX see https://medium.com/rahasak/nginx-reverse-proxy-with-url-rewrite-a3361a35623c.

**Comment by LelieL91** [comment]
> To quote the README.md: "We do not support directly changing the path where Synapse-Admin is served."
> 
> The path prefix cannot be changed via the `config.json` since this file itself has to be loaded from the prefix. So a dynamic configuration is not possible.
> 
> For NGINX see https://medium.com/rahasak/nginx-reverse-proxy-with-url-rewrite-a3361a35623c.

Thank you for your reply. I spent the whole afternoon trying to let it working using rewrite or different location syntax unsuccessfully. I saw in README.md you are providing just the traefik subpath example, but beside that I was hosting synapse-admin without any issue before the update.
So as a workaround, I just edited manually the script source (index.html) by adding my subpath and everything is working as expected:
FROM: `<script type="module" crossorigin src="/assets/index-DE-VvRNO.js"></script>`
TO: `<script type="module" crossorigin src="/subpath/assets/index-DE-VvRNO.js"></script>`

**Comment by becast** [comment]
You can just remove the first slash and serve it from any subdirectory this way. e.g. 
`<script type="module" crossorigin src="assets/index-DE-VvRNO.js"></script>`

Dunno why suddenly serving from a sub directory is not supported anymore...

**Comment by awesome-manuel** [comment]
It does not work anymore since we replace the deprecated `react-scripts` by `vitejs`.

The `react-scripts` replaced the placeholder `%PUBLIC_URL%` with the actual value of the environment variable. As I already mentioned above, you can achieve the same in your own builds using ` yarn build --base=/synapse-admin`.

But this is not possible and will never be possible with the prebuilt docker containers.
