### ISSUE TITLE
Nothing works..

### ISSUE THREAD

**Issue by tempuser0012** [Awesome-Technologies/synapse-admin#55]
I click a user and I get “element not found”, click on the rooms tab and it says “bad request”. Install on unraid used my url for matrix and local IP and literally nothing on this app works or opens..

**Comment by ptman** [comment]
What does the browser console say?

**Comment by awesome-michael** [comment]
What is the version of synapse you are trying to connect with? Some features used by synapse-admin are not implemented in older versions of synapse.

**Comment by dklimpel** [comment]
I could reproduce this behavior with synapse v1.9.1 which is outdated.

**Comment by awesome-manuel** [comment]
Closed, since there is no new information from the original author.
