### ISSUE TITLE
SSO Login support

### ISSUE THREAD

**Issue by ptman** [Awesome-Technologies/synapse-admin#56]
I'd like to manage a homeserver with SSO login, but this only seems to support password login?

**Comment by awesome-michael** [comment]
Currently only password login is supported. If you like to contribute a SSO login feel free to file a PR

**Comment by ptman** [comment]
Is there any way to give the access token taken from another client then?

**Comment by awesome-michael** [comment]
In the current state: no.
Can you describe your use-case?

**Comment by ptman** [comment]
Managing a server that uses SSO login

**Comment by awesome-michael** [comment]
Unfortunately I think thats not possible until an option for SSO login is implemented here.

**Comment by awesome-manuel** [comment]
We don't use `matrix-react-sdk` in this project, so this has to be implemented from scratch. Right now we do not have a sponsor for this, so it's not on our TODO list for the near future.

**Comment by tgurr** [comment]
Is this still being worked on? https://github.com/Awesome-Technologies/synapse-admin/pull/124 got closed and I found https://github.com/Awesome-Technologies/synapse-admin/pull/131 as a follow-up regarding zh-CN support part, but none for the SSO part.

**Comment by awesome-michael** [comment]
We asked to split the PRs in two but unfortunately only the zh-CN part was resubmitted. Also we couldn't test the SSO part and it's not on our TODO list.

**Comment by ptman** [comment]
so there's a PR that would solve this?
