### ISSUE TITLE
"Your session has ended, please reconnect", logout after succesfull logon from behind Traefik proxy

### ISSUE THREAD

**Issue by echtniels** [Awesome-Technologies/synapse-admin#63]
Running synapse-admin behind Traefik2 reverse proxy gives me the exact same results. User, password & homeserver are validated, the main screen opens (with info ghosted and a spinner top-right) and then returns me to the logon screen with the message "Your session has ended, please reconnect".

- No info shown on the docker logs
- Tried :latest and a few older releases
- Entering a random user or password fails so authentication DOES happen
- synapse-admin and synapse are both exposed by Traefik on port 443 on subdomains of the same domain

I found related issues 'closed' with the message that updating to the latest release should have fixed it but it does not for me.

**Comment by awesome-michael** [comment]
Do you login with an user account that has admin rights at the synapse server? I tested just now with an unprivileged account and the error message is exactly the one you get (I admit that it's a bit misleading)

If that's not the case:
Do you get error messages in the console of your browser that you could provide?  What is your synapse version?
What are your synapse settings for sessions? Did you configure a session timeout?

**Comment by echtniels** [comment]
That's awesome, Michael ;-) solving my issue in one try. Somehow oversaw I had not promoted myself to an admin role, corrected and it works flawless now.

Thanks a million for your quick help!
