### ISSUE TITLE
Login works but "Not Found" error when looking for records

### ISSUE THREAD

**Issue by zeigerpuppy** [Awesome-Technologies/synapse-admin#65]
I have installed synapse-admin with docker.
I am using the same domain as my matrix server to avoid and CORS issues -- something like this:
- server: https://matrix.myserver.net
- synapse-admin: https://matrix.myserver.net/admin

Sign in works and there are no browser console errors, no web server errors and no errors shown in the docker logs for synapse-admin.
However, I am unable to see details of users or rooms, whenever I try to load these details, a red "Not Found" error is shown on the bottom of the page.

Does anyone have any further suggestions for debugging?

**Comment by dklimpel** [comment]
Which synapse version is installed on your server?

**Comment by zeigerpuppy** [comment]
I am running the latest Debian version (for Stretch) - 1.19.0 

Also I did note some more information in the web browser console (Firefox)
I have included it here (replaced access token with XXXXXXXX):

```
getList users dataProvider.js:134:12
httpClient https://matrix.myserver.net/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id dataProvider.js:7:10
checkAuth XXXXXXXX authProvider.js:48:12
checkError 404 authProvider.js:39:12
```

So looks like a 404 is returned after the checkAuth is provided.
The debug line for that 404 is `authProvider.js:39:12`

It's a bit strange because logging in must also go through the auth step...

**Comment by zeigerpuppy** [comment]
OK, did a bit more digging through logs and found the 404 issue.

synapse-admin is calling api addresses on the URL:  https://matrix.myserver.net/_synapse/admin/v1/...
However, the matrix synapse server by default uses the extension `/_matrix` not `/_synapse`.

I added another direction in my reverse-proxy, to also server requests to `/_synapse` and now it works.

Shouldn't the default end point be used (`/_matrix`)?

**Comment by awesome-manuel** [comment]
synapse-admin need access to both since
 - `/_matrix` is used for login
 - `/_synapse` is used for the actual admin API (only legacy admin API is served via `_matrix`)

**Comment by virtadpt** [comment]
That fixed it for me, too - thanks!
