### ISSUE TITLE
Using synapse-admin from other adresses then 127.0.0.1

### ISSUE THREAD

**Issue by ralfi** [Awesome-Technologies/synapse-admin#66]
Hi,

it would very helpfull to use synapse-admin from other addresses like 127.0.0.1. Please can you adjust the docker file including docs?

**Comment by awesome-manuel** [comment]
I'm not sure what you refer to. How should the Dockerfile be changed?
There is nothing IP specific in the whole repository.

You typically use Docker to map ports between the container and your host computer.

**Comment by ralfi** [comment]
Hi Manuel,

thanks for your quick response. Let me explain a little bit more.

I just try to install synapse-admin via docker with matrix-docker-ansible-deploy. I am using this ansible script whithout nginx because i have a apache reverse proxy config for accessing all apache sub domains i am using with different urls from outside my network to my ip4 lan with ip4 docker adresses or ports.

Everything all for my matrix sub domains like matrix-configuration self or my selfhosted web interface or other selhosted apache sub domains works like this https://riot.FQDN and so on. Now i am looking for a solution to do this with synapse-admin. But everything i do synapse-admin let me connect only through 127.0.0.1:80 and not for <Local_IP_Docker_Host>:80.

Thanks in advance.

**Comment by awesome-manuel** [comment]
Can you attach the ansible script? Still I'm pretty sure this is nothing we could change inside the synapse-admin Docker container.

**Comment by ralfi** [comment]
Hi Manuel,

please take a look at this ...
https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/roles/matrix-synapse-admin

This is my apache config
![Bildschirmfoto vom 2020-09-01 09-45-20](https://user-images.githubusercontent.com/294423/91822891-b3f93980-ec38-11ea-8ea8-a9c4acfd2e42.png)

I can open the login page but after a setup the creadential nothing appears. IMHO it should be cause by apache config, ip address mistakes or something like this ...

**Comment by awesome-manuel** [comment]
> IMHO it should be cause by apache config, ip address mistakes or something like this ...

Then you should file the bug against https://github.com/spantaleev/matrix-docker-ansible-deploy
For debugging you can open the developer console in your browser and look at the console for any errors or at the network tab for any failed requests.

**Comment by ralfi** [comment]
The mistake was in front of the keyboard ...

I had to set to additional Proxy Pass and Reserve directives to redirect the _matrix and _synapse traffic to the encrypted Matrix Port 8008 and everything works.

Thanks that you can show me the way to this with the Browser debugging console ...
