### ISSUE TITLE
yarn install does not work?

### ISSUE THREAD

**Issue by fooness** [Awesome-Technologies/synapse-admin#67]
I followed the “Steps for 1)” …

- make sure you have installed the following: git, yarn, nodejs
- download the source code: git clone https://github.com/Awesome-Technologies/synapse-admin.git
- change into downloaded directory: cd synapse-admin
- download dependencies: yarn install
- start web server: yarn start

… which results in:

```
root@host:~/synapse-admin# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

```
root@host:~/synapse-admin# ls
Dockerfile  LICENSE  README.md  package.json  public  screenshots.jpg  src  yarn.lock
```

**Comment by awesome-michael** [comment]
I assume you are working on Ubuntu. It seems you have the wrong "yarn" installed. See https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by fooness** [comment]
Thank you for your reply. This seems to work, somewhat. It’s necessary to install node >= 10, too, from probably external resources … e.g. via `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`

Maybe this should be part of the README, in case others are having the same problems.

**Comment by fooness** [comment]
Now there’s one more problem, but I’m not sure it’s related to this issue …

<img width="391" alt="Screenshot 2020-09-02 at 13 54 23" src="https://user-images.githubusercontent.com/11408027/91978099-dddb5a80-ed23-11ea-9b72-854f08451393.png">

**Comment by awesome-michael** [comment]
Is the homeserver you configured reachable from your system? The network error may indicate that's not the case. Are there errors in the browsers console or in the network tab of the browsers developer tools?

**Comment by fooness** [comment]
It’s definitely reachable, I’m interacting with it through Element. No network errors, but some errors in the console, yes …

```
Navigated to http://<some_ip>/#/users
The development server has disconnected.
Refresh the page if necessary. 0.chunk.js:152786:13
[HMR] Waiting for update signal from WDS... log.js:24
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:24994
checkAuth […] authProvider.js:48
getList users dataProvider.js:134
httpClient https://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id dataProvider.js:7
checkAuth […] authProvider.js:48
XHROPTIONShttps://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id
[HTTP/1.1 404 Not Found 46ms]
TypeError: NetworkError when attempting to fetch resource. index.js:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id. (Reason: CORS request did not succeed).
checkError undefined 2 authProvider.js:39
Warning: Missing translation for key: "NetworkError when attempting to fetch resource."
```

**Comment by awesome-michael** [comment]
The 404 error could mean that the endpoint is not correct (which version of synapse are you talking to? The latest version of synapse-admin need synapse to be at least v1.18.0)
But maybe the CORS errors are the problem. Maybe the server running synapse does not set the correct headers?

**Comment by fooness** [comment]
synapse shouldn’t be the problem.

```
root@host:/var/www/element# dpkg -l | grep matrix-synapse
ii  matrix-synapse-py3             1.19.0+bionic1                      amd64        Open federated Instant Messaging and VoIP server
```

I don’t think we do set any headers manually … is there some way to, hm, allow the access from the interface-server-ip? I don’t really know that much about CORS headers. But, I mean, we can connect to our homeserver from Element Desktop, too, so I wouldn’t quite understand why the connection from the interface would not work.

**Comment by fooness** [comment]
I just tried adding the following to my homeserver’s nginx sites file, as seen in: https://serverfault.com/a/716283

```
  location /_synapse {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
     }
  }
```

Still results in errors:

```
GEThttps://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id
[HTTP/1.1 404 Not Found 33ms]

TypeError: NetworkError when attempting to fetch resource. index.js:1

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://some.domain/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Maybe the CORS is not the problem, but why is this error 404 shown there in the first line?

**Comment by fooness** [comment]
Maybe related: https://github.com/Awesome-Technologies/synapse-admin/issues/65

My nginx config is as described in the synapse docs …

```
  location /_matrix {
    proxy_pass http://127.0.0.1:8008;
    proxy_set_header X-Forwarded-For $remote_addr;
    client_max_body_size 10M;
  }
```

**Comment by awesome-michael** [comment]
Seems your nginx config is missing the _synapse endpoint which is used by the admin api. Hence the 404
