### ISSUE TITLE
wrong home_server domain in localstorage

### ISSUE THREAD

**Issue by teutat3s** [Awesome-Technologies/synapse-admin#7]
Hello, thank you for this nice matrix admin panel!

I noticed that for some reason the `home_server` variable that's stored in local storage gets set with a wrong value with our instance.

Our synapse server answers at `matrix.example.com`, but the value in local storage gets set to `example.com`.
When I change the value by hand, everything works fine. What's weird is that login works fine...
Only after login I got errors about unable to fetch resource (it's trying the wrong domain ofc)

Is this value taken from the synapse instance? Is this a bug or a misconfiguration of our synapse server?

**Comment by awesome-manuel** [comment]
Have a look at https://github.com/Awesome-Technologies/synapse-admin/blob/master/src/synapse/authProvider.js
The `home_server` is set from the response to the login request.

**Comment by teutat3s** [comment]
I did a quick test with `Insomnia` to check the json that gets returned from the login request.
It seems `home_server` should be `base_url`

```
{
  "user_id": "@user:example.com",
  "access_token": "REDACTED",
  "home_server": "example.com",
  "device_id": "REDACTED",
  "well_known": {
    "m.homeserver": {
      "base_url": "https://matrix.example.com/"
    }
  }
}
```

**Comment by awesome-manuel** [comment]
Right, so we need to decide how the admin interface should handle this.
Riot resolves the server name from the homeserver part of the user id using a GET request to a special `.well-known` URL, or it lets you define the URL yourself.
We could do the same or we could always request the server URL (not the homeserver name) and allow login only using the local part of the user id.
