### ISSUE TITLE
Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by JOJ0** [Awesome-Technologies/synapse-admin#71]
Hi, installed the docker container on my synapse host and can successfully log in with an admin account to synapse-admin but it doesn't show any users or rooms. Synapse-admin shows this message on the bottom:

Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.

Some more info on my workflow:

I started the container using:

`sudo docker run -p 8080:80 awesometechnologies/synapse-admin`

I redirected synapse-admin to my local mac machine by using an ssh tunnel:

`ssh -L 8080:localhost:8080 my-host.fqdn`

and viewed the web-ui in my local webrowser (Safari) by accessing this url:

http://localhost:8080

I must have missed something. Thanks for pointing me in the right direction!

all the best
Jojo

**Comment by awesome-manuel** [comment]
CORS must be configured for your synapse, see https://github.com/matrix-org/synapse/issues/1595
You can also use a Reverse-Proxy with CORS.
Anyway this is not an issue of synapse-admin.

**Comment by dklimpel** [comment]
Is it an option to build synapse-admin with `INLINE_RUNTIME_CHUNK=false yarn build` ?
