### ISSUE TITLE
NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by Cam-B** [Awesome-Technologies/synapse-admin#75]
I'm on Synapse admin version 0.5.0. When I log in as admin I get 
"NetworkError when attempting to fetch resource" as a red popup bar at the bottom of the page. 

Synapse Admin does recognize admin creds, so it's obviously communicating with the homeserver. 

What should I look in to for troubleshooting?

**Comment by virtadpt** [comment]
Double-check your nginx/apache proxying settings.  Make sure that you're forwarding URLs that start with /_synapse

**Comment by Cam-B** [comment]
Thanks for the quick response @virtadpt. Will check on this.

**Comment by awesome-manuel** [comment]
Duplicate of #76 and #65
