### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by hmn566** [Awesome-Technologies/synapse-admin#76]
When I login to synapse admin. I get erro failed to fetch and no user will showed up

**Comment by awesome-michael** [comment]
What versions of synapse and synapse-admin do you use? If your synapse version is too low some endpoints that synapse-admin uses may not exist.

**Comment by hmn566** [comment]
This is synapse version
{"versions":["r0.0.1","r0.1.0","r0.2.0","r0.3.0","r0.4.0","r0.5.0","r0.6.0"],"unstable_features":{"org.matrix.label_based_filtering":true,"org.matrix.e2e_cross_signing":true,"org.matrix.msc2432":true,"uk.half-shot.msc2666":true,"io.element.e2ee_forced.public":false,"io.element.e2ee_forced.private":false,"io.element.e2ee_forced.trusted_private":false}}

i don't know syanpse-admin version but i installed it last week

**Comment by dklimpel** [comment]
You can get your server version with this: `/_synapse/admin/v1/server_version`

Looks like this:
`{"server_version":"1.21.2","python_version":"3.6.9"}`

Also you can see it in synapse-admin login screen:
![image](https://user-images.githubusercontent.com/5740567/97082241-96c56380-1608-11eb-9d39-a8dc86c0d4da.png)

**Comment by hmn566** [comment]
/_synapse/admin/v1/server_version
<blockquote class="imgur-embed-pub" lang="en" data-id="OmNUxD5"><a href="https://imgur.com/OmNUxD5">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by dklimpel** [comment]
See here: https://github.com/Awesome-Technologies/synapse-admin/issues/65#issuecomment-682236014
You do not redirect `/_synapse` to your Synapse server

**Comment by hmn566** [comment]
Thanks.
It says " I added another direction in my reverse-proxy, to also serve requests to /_synapse and now it works."
How to do that?

**Comment by dklimpel** [comment]
It depends from your webserver.
Please use google or something else.
You can also find information here: https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md
