### ISSUE TITLE
After doing it production?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Awesome-Technologies/synapse-admin#77]
I run perfect with yarn start, but I decided to make it production
```
Compiled successfully.

File sizes after gzip:

  362.06 KB  build/static/js/2.2b6cdba9.chunk.js
  11.03 KB   build/static/js/main.3804f478.chunk.js
  779 B      build/static/js/runtime-main.610dcd3c.js

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  bit.ly/CRA-deploy

Done in 36.96s.

```
My question, after compiling it for production supposedly how does it run, anyway? yarn start?

**Comment by dklimpel** [comment]
You need only a webserver like Nginx, Apache, etc. and point to the `build` directory.
You can also move the directory at any location / server you want.

**Comment by AnonymousWebHacker** [comment]
I already noticed that inside build, there is the index, thank you very much

**Comment by AnonymousWebHacker** [comment]
I already noticed that inside build, there is the index, thank you very much
