### ISSUE TITLE
Latest Synapse Version doesn't allow new user creation

### ISSUE THREAD

**Issue by fancycade** [Awesome-Technologies/synapse-admin#80]
Hi there,

Running into a strange issue when trying to create a new user. I am able to login, and /_synapse/admin is exposed, but when I create a new user I get this issue on the server side.

```
SynapseError: 400 - This endpoint can only be used with local users
```

This is strange to me because I have been able to successfully do this before with other versions of Synapse.

I believe the version of synapse I'm running is v1.22.0, but I'm not sure because I'm using the synapse:latest tag. However, it was only a few days ago. Whereas the version of Synapse I used successfully was from a few weeks ago.

I'm hoping there is a work around because this issue invalidates synapse-admin's use case for me.

I realize this is an issue on Synapse's side, but it really only affects apps like this. Curious if others have seen this issue.

**Comment by awesome-manuel** [comment]
Please check the user ID that you try to create. The domain part must match your server!
The error comes from the server and is not caused by synapse admin UI.
