### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by dklimpel** [Awesome-Technologies/synapse-admin#81]
Is there an bug or not?
The button links to `/importcsv`
https://github.com/Awesome-Technologies/synapse-admin/blob/e5d2d895d9add862eff131c5f7ef2439f13ae7f1/src/components/users.js#L48-L52

I get:
![image](https://user-images.githubusercontent.com/5740567/98222442-1f20fe00-1f51-11eb-81bb-b45588a206cb.png)

The import mask is reachable by `/import_users`
https://github.com/Awesome-Technologies/synapse-admin/blob/e5d2d895d9add862eff131c5f7ef2439f13ae7f1/src/App.js#L32-L34

**Comment by awesome-michael** [comment]
That seems to be a bug. We decided to rename the path to be more generic, so it should be "/import_users" in the users.js. Thanks for pointing out
