### ISSUE TITLE
NetworkError 

### ISSUE THREAD

**Issue by mdcnick** [Awesome-Technologies/synapse-admin#98]
NetworkError when attempting to fetch resource.

im having a problem understanding how to get the     /_matrix
    /_synapse/admin

see photo
https://imgur.com/GZrsnad

**Comment by muh2000** [comment]
did you figure it out?

**Comment by muh2000** [comment]
i had to adjust my reverse proxy for the /_synapse/admin path

**Comment by rufflepot** [comment]
> 
> 
> i had to adjust my reverse proxy for the /_synapse/admin path

Hey there. I'm having the same issue and was wondering in what way you adjusted it. I'm using nginx if it matters but any info at all would be helpful.

**Comment by zell-mbc** [comment]
@muh2000 , same here, some help to get nginx configured would be really appreciated.

**Comment by zell-mbc** [comment]
Quick update, I found a nginx setting which works for me. You need to add the synapse/admin url to your location.
Here's my setting:
```location ~* ^(\/_matrix|\/_synapse\/admin|\/_synapse\/client) {```
